# Generated by Django 3.1 on 2021-05-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app_api', '0002_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_description',
            field=models.CharField(max_length=500),
        ),
    ]
